// HEALING — ĐỘNG LỰC & TIẾN LÊN
const healingDongluc = [
  { id: 146, text: "Bắt đầu nhỏ thôi nhưng nhất định phải bắt đầu", category: "dongluc" },
  { id: 147, text: "Bạn không cần cảm hứng chỉ cần bắt đầu", category: "dongluc" },
  { id: 148, text: "Một bước tiến nhỏ hôm nay hơn mười bước tiến trong mơ", category: "dongluc" },
  { id: 149, text: "Bạn đã đi xa hơn điểm xuất phát rất nhiều rồi", category: "dongluc" },
  { id: 150, text: "Mỗi ngày làm tốt hơn ngày hôm qua một chút thôi", category: "dongluc" },
  { id: 151, text: "Sự kiên trì của bạn sẽ làm người tương lai biết ơn", category: "dongluc" },
  { id: 152, text: "Không ai thành công mà không có những ngày muốn bỏ cuộc", category: "dongluc" },
  { id: 153, text: "Tiềm năng của bạn lớn hơn nỗi sợ của bạn", category: "dongluc" },
  { id: 154, text: "Hôm nay bạn cố gắng là đang đầu tư cho bản thân tương lai", category: "dongluc" },
  { id: 155, text: "Bạn có thể làm được điều khó khi bạn quyết định thử", category: "dongluc" },
  { id: 156, text: "Mỗi lần bạn không bỏ cuộc là một chiến thắng ngầm", category: "dongluc" },
  { id: 157, text: "Hãy tin rằng phiên bản tốt hơn của bạn đang được tạo ra", category: "dongluc" },
  { id: 158, text: "Đích đến quan trọng nhưng người bạn trở thành trên đường quan trọng hơn", category: "dongluc" },
  { id: 159, text: "Bạn không cần ai cho phép để bắt đầu điều bạn muốn", category: "dongluc" },
  { id: 160, text: "Ngày mai sẽ cảm ơn hôm nay vì đã không bỏ cuộc", category: "dongluc" },
  { id: 356, text: "Thêm một lần thử là thêm một cơ hội để khác đi", category: "dongluc" },
  { id: 357, text: "Bạn không cần hoàn hảo để tiến bộ chỉ cần tiếp tục", category: "dongluc" },
  { id: 358, text: "Những ngày ít động lực vẫn có thể trở thành ngày nhiều kỷ luật", category: "dongluc" },
  { id: 359, text: "Mục tiêu lớn được tạo nên từ những việc nhỏ làm đều đặn", category: "dongluc" },
  { id: 360, text: "Bạn đã có đủ thứ cần thiết cho bước đầu tiên rồi", category: "dongluc" },
  { id: 361, text: "Sự tự tin thường đến sau hành động chứ không đến trước", category: "dongluc" },
  { id: 362, text: "Đừng coi thường một ngày bình thường nếu hôm nay bạn vẫn cố gắng", category: "dongluc" },
  { id: 363, text: "Mỗi việc hoàn thành là một viên gạch xây lòng tin vào bản thân", category: "dongluc" },
  { id: 364, text: "Bạn có quyền đi chậm miễn là đừng bỏ hẳn con đường", category: "dongluc" },
  { id: 365, text: "Có thể hôm nay khó nhưng bạn không còn là người của ngày hôm qua", category: "dongluc" },
  { id: 366, text: "Kỷ luật dịu dàng với bản thân sẽ đi xa hơn trách móc liên tục", category: "dongluc" },
  { id: 367, text: "Đi tiếp dù còn nghi ngờ cũng là một dạng dũng cảm", category: "dongluc" },
  { id: 368, text: "Thành công không đến trong một đêm nhưng nỗ lực hôm nay vẫn có ý nghĩa", category: "dongluc" },
  { id: 369, text: "Bạn được phép tự hào về những bước nhỏ mà người khác không thấy", category: "dongluc" },
  { id: 370, text: "Chỉ cần hôm nay tốt hơn một chút là đã đủ để tiếp tục", category: "dongluc" },
  { id: 591, text: "Bạn không cần đợi hết sợ mới bắt đầu tiến lên", category: "dongluc" },
  { id: 592, text: "Một thói quen nhỏ bền bỉ sẽ mạnh hơn một lần hứng khởi lớn", category: "dongluc" },
  { id: 593, text: "Hôm nay chỉ cần làm điều quan trọng nhất trước là đã thắng rồi", category: "dongluc" },
  { id: 594, text: "Bạn có thể chậm nhưng đừng quên mình vẫn đang đi", category: "dongluc" },
  { id: 595, text: "Mỗi nỗ lực lặng thầm đều đang âm thầm đổi tương lai của bạn", category: "dongluc" },
  { id: 596, text: "Điều bạn làm đều đặn quan trọng hơn điều bạn hứa thật hay", category: "dongluc" },
  { id: 597, text: "Bạn mạnh hơn rất nhiều khi dám quay lại sau một lần ngã", category: "dongluc" },
  { id: 598, text: "Không sao nếu hôm nay tiến ít miễn là vẫn giữ lời với chính mình", category: "dongluc" },
  { id: 599, text: "Có những cánh cửa chỉ mở ra sau nhiều ngày kiên trì gõ nhẹ", category: "dongluc" },
  { id: 600, text: "Bạn không cần phải đốt mình sáng rực chỉ cần sáng đều đặn", category: "dongluc" },
  { id: 601, text: "Mỗi ngày giữ lời với bản thân một chút là tự tin sẽ lớn dần", category: "dongluc" },
  { id: 602, text: "Áp lực không luôn là dấu chấm hết đôi khi là tín hiệu bạn đang lớn", category: "dongluc" },
  { id: 603, text: "Bạn có thể làm việc khó bằng cách chia nó thành những bước nhỏ", category: "dongluc" },
  { id: 604, text: "Bền bỉ là khi bạn quay lại sau ngày không như ý", category: "dongluc" },
  { id: 605, text: "Đừng quên ghi nhận mình vì những phần việc đã hoàn thành", category: "dongluc" },
  { id: 606, text: "Bạn có quyền tự tạo nhịp tiến bộ phù hợp với mình", category: "dongluc" },
  { id: 607, text: "Ngày khó không xóa được công sức bạn đã tích lũy trước đó", category: "dongluc" },
  { id: 608, text: "Tiến bộ không ồn ào nên nhiều khi bạn quên mất mình đã lớn", category: "dongluc" },
  { id: 609, text: "Hãy làm nốt việc nhỏ này rồi bạn sẽ thấy mình mạnh hơn một chút", category: "dongluc" },
  { id: 610, text: "Con đường dài luôn được đi qua bằng những bước rất bình thường", category: "dongluc" },
  { id: 941, text: "Bạn không cần làm hết hôm nay chỉ cần không bỏ luôn ngày mai", category: "dongluc" },
  { id: 942, text: "Mỗi việc nhỏ hoàn thành là một cách nhắc mình có thể làm được", category: "dongluc" },
  { id: 943, text: "Đừng xem nhẹ những ngày bạn vẫn tiếp tục dù không ai cổ vũ", category: "dongluc" },
  { id: 944, text: "Bạn mạnh nhất không phải khi không ngã mà khi biết đứng dậy", category: "dongluc" },
  { id: 945, text: "Có những bước rất nhỏ nhưng đủ để đổi hướng cả chặng đường", category: "dongluc" },
  { id: 946, text: "Bạn không cần cảm thấy sẵn sàng hoàn toàn mới được bắt đầu", category: "dongluc" },
  { id: 947, text: "Một ngày đều đặn luôn đáng giá hơn một ngày bùng nổ rồi biến mất", category: "dongluc" },
  { id: 948, text: "Mỗi lần bạn quay lại với mục tiêu là một lần chiến thắng bản thân", category: "dongluc" },
  { id: 949, text: "Tiến bộ không cần nhanh chỉ cần thật", category: "dongluc" },
  { id: 950, text: "Bạn có thể chưa tới nơi nhưng đã khác rất nhiều so với điểm đầu", category: "dongluc" },
  { id: 951, text: "Những việc lặp lại hàng ngày đang xây nên phiên bản bền bỉ của bạn", category: "dongluc" },
  { id: 952, text: "Hôm nay làm một chút vẫn tốt hơn chờ ngày hoàn hảo mới bắt đầu", category: "dongluc" },
  { id: 953, text: "Bạn không cần chạy rất nhanh để vượt qua người từng là mình", category: "dongluc" },
  { id: 954, text: "Khi mệt hãy nghỉ một nhịp rồi quay lại thay vì tự trách", category: "dongluc" },
  { id: 955, text: "Mỗi lần giữ lời với chính mình là tự tin lại lớn thêm một chút", category: "dongluc" },
  { id: 956, text: "Có những ngày bình thường nhưng chính sự đều đặn làm nên phép màu", category: "dongluc" },
  { id: 957, text: "Bạn có thể xây điều lớn lao bằng những thói quen rất giản dị", category: "dongluc" },
  { id: 958, text: "Đừng đợi hết hoang mang mới tiếp tục nhiều người vẫn đi tiếp khi còn run", category: "dongluc" },
  { id: 959, text: "Bạn xứng đáng tự ghi nhận cả những cố gắng không ai thấy", category: "dongluc" },
  { id: 960, text: "Mỗi lần nói để mình thử xem là một cánh cửa mới mở ra", category: "dongluc" },
  { id: 961, text: "Bạn không thua chỉ vì hôm nay chậm hơn dự định", category: "dongluc" },
  { id: 962, text: "Con đường bền vững thường được đi bằng sự kiên trì âm thầm", category: "dongluc" },
  { id: 963, text: "Bạn có thể tự hào vì đã quay lại dù từng muốn bỏ", category: "dongluc" },
  { id: 964, text: "Những ngày thiếu động lực vẫn có thể trở nên có ý nghĩa bằng hành động nhỏ", category: "dongluc" },
  { id: 965, text: "Tiến về phía trước một milimet vẫn là đang tiến", category: "dongluc" },
  { id: 966, text: "Bạn đang đi đúng nếu mỗi ngày đều học được chút gì đó về mình", category: "dongluc" },
  { id: 967, text: "Hãy để bản thân tiến bộ theo cách không làm mình gãy", category: "dongluc" },
  { id: 968, text: "Điều đáng nể nhất đôi khi là bạn vẫn ở lại với mục tiêu của mình", category: "dongluc" },
  { id: 969, text: "Một bước nữa thôi cũng có thể đưa bạn qua đoạn khó nhất", category: "dongluc" },
  { id: 970, text: "Bạn không cần phi thường chỉ cần bền bỉ hơn hôm qua một chút", category: "dongluc" },
];
