// TROLL — CRUSH & TÌNH YÊU
const trollCrush = [
  { id: 1, text: "Crush rep chậm là đang chat với người khác à", category: "crush" },
  { id: 2, text: "Thà ế chứ không thà yêu lại người cũ", category: "crush" },
  { id: 3, text: "Crush online mà không like story thì coi như xong", category: "crush" },
  { id: 4, text: "Yêu xa là yêu cái nỗi nhớ thôi chứ yêu gì người", category: "crush" },
  { id: 5, text: "Single vì chuẩn cao chứ không phải vì ế đâu nha", category: "crush" },
  { id: 6, text: "Người ta đổi trạng thái còn mình đổi ảnh đại diện", category: "crush" },
  { id: 7, text: "Chat vui lắm rồi để đấy quên rep luôn", category: "crush" },
  { id: 8, text: "Crush đăng story với người khác mà bảo bạn thân", category: "crush" },
  { id: 9, text: "Thất tình rồi lại lên mạng đọc quote buồn", category: "crush" },
  { id: 10, text: "Ngày Valentine mình với con mèo nhìn nhau rồi cười", category: "crush" },
  { id: 11, text: "Mình thích bạn nhưng bạn thích người thích bạn của mình", category: "crush" },
  { id: 12, text: "Nói chuyện mỗi ngày mà bảo chúng mình chỉ là bạn", category: "crush" },
  { id: 13, text: "Duyên phận là câu chuyện mà số phận viết sai chính tả", category: "crush" },
  { id: 14, text: "Seen rồi không rep là cũng một dạng bạo lực tinh thần", category: "crush" },
  { id: 15, text: "Thích ai mà không dám nói thì khác gì mua vé mà không đi xem phim", category: "crush" },
  { id: 161, text: "Crush thả tim bài đăng cũ làm tim mình lag một nhịp", category: "crush" },
  { id: 162, text: "Tỏ tình trong đầu cả trăm lần ra đời chỉ dám chào bạn", category: "crush" },
  { id: 163, text: "Nghe nhạc love song mà người yêu thì chưa có bản demo", category: "crush" },
  { id: 164, text: "Crush đổi avatar là mình phân tích như chuyên gia tình báo", category: "crush" },
  { id: 165, text: "Tình yêu đẹp nhất là tình yêu chưa bắt đầu nên chưa đau", category: "crush" },
  { id: 166, text: "Mập mờ lâu quá đến lúc rõ ràng thì thành người dưng", category: "crush" },
  { id: 167, text: "Bạn thân bảo đừng thích nữa nhưng trái tim không cài được", category: "crush" },
  { id: 168, text: "Crush cười một cái là nguyên ngày mình quên cả deadline", category: "crush" },
  { id: 169, text: "Nói là không quan tâm nhưng story nào của crush cũng xem đầu", category: "crush" },
  { id: 170, text: "Đã thích người ta rồi thì red flag cũng nhìn thành đèn lồng", category: "crush" },
  { id: 171, text: "Tình đơn phương là môn thể thao đốt năng lượng mà không có huy chương", category: "crush" },
  { id: 172, text: "Crush hỏi mượn bài là tim mình tự động mở quyền chỉnh sửa", category: "crush" },
  { id: 173, text: "Nửa đêm nhớ người ta xong sáng ra vẫn phải đi làm như thường", category: "crush" },
  { id: 174, text: "Thính người ta thả trúng ai không biết chứ mình dính đầu tiên", category: "crush" },
  { id: 175, text: "Yêu đương gì tầm này khi tin nhắn còn phải nghĩ ba phút mới gửi", category: "crush" },
  { id: 371, text: "Crush chỉ cần hỏi đang làm gì là mình muốn kể cả tiểu sử", category: "crush" },
  { id: 372, text: "Đã bảo quên người ta rồi mà playlist vẫn toàn nhạc nhớ", category: "crush" },
  { id: 373, text: "Crush vô tình đứng gần là não mình tự động treo máy", category: "crush" },
  { id: 374, text: "Một cái haha của crush cũng đủ làm mình phân tích nửa ngày", category: "crush" },
  { id: 375, text: "Muốn làm người yêu crush nhưng hiện tại mới làm khán giả story", category: "crush" },
  { id: 376, text: "Nói không thích nữa nhưng hễ nghe tên người ta là quay đầu", category: "crush" },
  { id: 377, text: "Crush rep một chữ mà mình rep lại như viết thư xin việc", category: "crush" },
  { id: 378, text: "Đơn phương lâu ngày khiến mình giỏi tưởng tượng hơn giỏi yêu", category: "crush" },
  { id: 379, text: "Yêu thầm mệt nhất là không có tư cách để giận", category: "crush" },
  { id: 380, text: "Crush đăng ảnh mới là mình vô xem nhanh hơn nhận lương", category: "crush" },
  { id: 381, text: "Tình cảm của mình rõ ràng còn tình trạng của hai đứa thì mờ", category: "crush" },
  { id: 382, text: "Đôi lúc chỉ cần crush chào buổi sáng là mình sống tử tế cả ngày", category: "crush" },
  { id: 383, text: "Bật cười với cả thế giới nhưng nhắn cho crush thì run tay", category: "crush" },
  { id: 384, text: "Crush chưa yêu mình nhưng đã dạy mình đủ kiểu chờ đợi", category: "crush" },
  { id: 385, text: "Mỗi lần định buông là người ta lại xuất hiện đúng lúc", category: "crush" },
  { id: 386, text: "Tự nhủ không xem nữa nhưng story của crush như nam châm", category: "crush" },
  { id: 387, text: "Mối quan hệ chưa bắt đầu mà mình đã tưởng tượng chia tay ba lần", category: "crush" },
  { id: 388, text: "Người ta vô tư còn mình âm thầm viết cả bộ phim tình cảm", category: "crush" },
  { id: 389, text: "Crush cười với ai cũng vậy nhưng mình lại tưởng có ngoại lệ", category: "crush" },
  { id: 390, text: "Có những người chỉ cần tồn tại là đủ khiến tim mình mất bình tĩnh", category: "crush" },
  { id: 611, text: "Crush rep sau hai tiếng mà mình vẫn trả lời trong ba giây", category: "crush" },
  { id: 612, text: "Mình không thích suy diễn nhưng crush đổi nhạc là mình nghĩ nhiều", category: "crush" },
  { id: 613, text: "Chỉ cần người ta hỏi ăn gì chưa là tim mình mở tiệc", category: "crush" },
  { id: 614, text: "Crush xem story trễ thôi mà mình tưởng như có tín hiệu vũ trụ", category: "crush" },
  { id: 615, text: "Tình cảm của mình chân thành đến mức tự làm khổ bản thân", category: "crush" },
  { id: 616, text: "Có những tối chỉ ngồi nghĩ xem nhắn gì cho đỡ kỳ", category: "crush" },
  { id: 617, text: "Thích người ta xong kỹ năng quan sát tăng như điệp viên", category: "crush" },
  { id: 618, text: "Crush thả haha mà mình đọc thành thơ tình", category: "crush" },
  { id: 619, text: "Biết người ta vô tư nhưng lòng mình cứ xin thêm hi vọng", category: "crush" },
  { id: 620, text: "Yêu thầm giống như giữ bí mật mà tim cứ muốn bật mí", category: "crush" },
  { id: 621, text: "Mỗi lần lướt qua đoạn chat cũ là mình tự làm mình rung động lại", category: "crush" },
  { id: 622, text: "Crush gửi icon thôi mà mình nghĩ chắc hợp nhau lắm", category: "crush" },
  { id: 623, text: "Không phải mình ảo tưởng chỉ là trí tưởng tượng làm việc hơi tích cực", category: "crush" },
  { id: 624, text: "Người ta lạnh nhạt một chút là playlist của mình tự động buồn", category: "crush" },
  { id: 625, text: "Mình thích người ta theo kiểu rất rõ nhưng mối quan hệ thì không", category: "crush" },
  { id: 626, text: "Có hôm chỉ muốn dứt mà crush xuất hiện đúng góc đẹp nhất", category: "crush" },
  { id: 627, text: "Tỏ tình khó nhất không phải nói ra mà là chấp nhận kết quả", category: "crush" },
  { id: 628, text: "Mỗi lần thấy tên người ta hiện lên là tim quên cách bình thường", category: "crush" },
  { id: 629, text: "Bạn bè khuyên nhiều lắm nhưng trái tim mình thích làm trái luật", category: "crush" },
  { id: 630, text: "Crush chưa làm gì sai chỉ là làm mình nghĩ hơi nhiều", category: "crush" },
  { id: 631, text: "Mập mờ là trạng thái khiến mình vừa vui vừa mệt rất nghệ thuật", category: "crush" },
  { id: 632, text: "Tình yêu đẹp nhất trong đầu mình thường chưa kịp ra đời thực", category: "crush" },
  { id: 633, text: "Crush nhắn ngủ ngon là mình có thêm lý do sống tử tế", category: "crush" },
  { id: 634, text: "Thích người thông minh mà bản thân lại cư xử rất thiếu tỉnh táo", category: "crush" },
  { id: 635, text: "Chờ người ta chủ động lâu quá nên mình thuộc luôn cách kiên nhẫn", category: "crush" },
  { id: 636, text: "Có những mối crush chỉ tồn tại để dạy mình cách buông đẹp", category: "crush" },
  { id: 637, text: "Nghĩ là sẽ hết thích nhưng càng gặp lại càng khó quên", category: "crush" },
  { id: 638, text: "Crush cười một cái là kế hoạch lý trí của mình vỡ hết", category: "crush" },
  { id: 639, text: "Yêu thầm lâu ngày khiến mình có tài viết kịch bản không công", category: "crush" },
  { id: 640, text: "Điều buồn nhất là mình nghiêm túc còn người ta chỉ lịch sự", category: "crush" },
];
