// TROLL — TRIẾT LÝ VỈA HÈ
const trollTrietly = [
  { id: 81, text: "Người thất bại hay nói về tương lai", category: "trietly" },
  { id: 82, text: "Cứ tưởng trưởng thành là hiểu mọi thứ hóa ra là lo lắng nhiều hơn", category: "trietly" },
  { id: 83, text: "Sống đơn giản là câu nói của người không có vấn đề", category: "trietly" },
  { id: 84, text: "Mọi chuyện rồi sẽ ổn là câu an ủi của kẻ bất lực", category: "trietly" },
  { id: 85, text: "Yêu bản thân là dễ nói nhất và khó làm nhất", category: "trietly" },
  { id: 86, text: "Người hạnh phúc không cần khoe hạnh phúc", category: "trietly" },
  { id: 87, text: "Ta cứ nghĩ mình độc đáo hóa ra ai cũng vậy", category: "trietly" },
  { id: 88, text: "Mạng xã hội dạy ta so sánh cuộc đời người khác với nỗi đau của mình", category: "trietly" },
  { id: 89, text: "Cố gắng không đảm bảo thành công nhưng không cố thì chắc chắn không có", category: "trietly" },
  { id: 90, text: "Ta sợ thất bại hơn là ta muốn thành công", category: "trietly" },
  { id: 291, text: "Đôi khi bình yên chỉ là không phải trả lời tin nhắn nào thêm", category: "trietly" },
  { id: 292, text: "Người lớn hay khuyên nhau mạnh mẽ trong khi ai cũng đang mỏi", category: "trietly" },
  { id: 293, text: "Sự thật thường đơn giản nhưng lòng người thích làm nó phức tạp", category: "trietly" },
  { id: 294, text: "Ta nghĩ mình chọn cuộc đời nhưng nhiều lúc chỉ đang chọn ít tiếc nuối hơn", category: "trietly" },
  { id: 295, text: "Càng lớn càng hiểu im lặng không phải lúc nào cũng là đồng ý", category: "trietly" },
  { id: 296, text: "Nỗi buồn trưởng thành là vẫn phải hoạt động bình thường khi trong lòng rối", category: "trietly" },
  { id: 297, text: "Thời gian không chữa lành tất cả nó chỉ dạy ta sống cùng vết xước", category: "trietly" },
  { id: 298, text: "Có những câu xin lỗi đến đúng nhưng quá muộn để cứu điều gì", category: "trietly" },
  { id: 299, text: "Con người hay nhớ điều mình mất hơn điều mình đang có", category: "trietly" },
  { id: 300, text: "Tự do đôi khi không phải có tất cả mà là dám bỏ bớt", category: "trietly" },
  { id: 301, text: "Điều khó nhất không phải hiểu người khác mà là hiểu mình đang muốn gì", category: "trietly" },
  { id: 302, text: "Nhiều mối quan hệ tan đi không vì ghét mà vì không còn sức giữ", category: "trietly" },
  { id: 303, text: "Ta thường tiếc tuổi trẻ khi đã dùng nó để lo lắng quá nhiều", category: "trietly" },
  { id: 304, text: "Có những ngày sống sót qua thôi cũng đã là cố gắng lớn", category: "trietly" },
  { id: 305, text: "Bài học đắt nhất thường đến vào lúc ví tiền lẫn tinh thần đều mỏng", category: "trietly" },
  { id: 306, text: "Không phải ai hiểu đạo lý cũng biết cách sống nhẹ nhàng", category: "trietly" },
  { id: 307, text: "Nhiều người tìm ý nghĩa cuộc đời trong khi bản thân chỉ cần nghỉ ngơi", category: "trietly" },
  { id: 308, text: "Càng muốn kiểm soát mọi thứ ta càng dễ bị mọi thứ kéo đi", category: "trietly" },
  { id: 309, text: "Sự tử tế không luôn được đáp lại nhưng thiếu nó thì đời càng cứng", category: "trietly" },
  { id: 310, text: "Ta học cách buông bỏ không phải vì yếu mà vì không muốn gãy thêm", category: "trietly" },
  { id: 511, text: "Đôi khi điều làm ta mệt không phải cuộc sống mà là kỳ vọng của chính mình", category: "trietly" },
  { id: 512, text: "Nhiều câu trả lời đến muộn hơn lúc ta còn cần chúng", category: "trietly" },
  { id: 513, text: "Con người thường tiếc điều đã quen hơn là điều thật sự phù hợp", category: "trietly" },
  { id: 514, text: "Ta muốn được hiểu nhưng lại giỏi che giấu nhất khi buồn", category: "trietly" },
  { id: 515, text: "Bình yên không phải nơi không có tiếng ồn mà là nơi lòng bớt tranh cãi", category: "trietly" },
  { id: 516, text: "Nhiều nỗi đau không đến từ chuyện xảy ra mà từ điều ta tưởng tượng thêm", category: "trietly" },
  { id: 517, text: "Có những người chỉ bước qua đời ta để dạy một bài học rất ngắn", category: "trietly" },
  { id: 518, text: "Ta dễ tha thứ cho người khác hơn cho phiên bản cũ của mình", category: "trietly" },
  { id: 519, text: "Điều đáng sợ không phải đổi thay mà là ở mãi nơi khiến mình héo đi", category: "trietly" },
  { id: 520, text: "Khi còn trẻ ta muốn được công nhận khi lớn hơn chỉ muốn được yên", category: "trietly" },
  { id: 521, text: "Không phải cánh cửa nào đóng lại cũng là mất mát đôi khi là cứu mình", category: "trietly" },
  { id: 522, text: "Ta càng trưởng thành càng hiểu có những chuyện không cần thắng thua", category: "trietly" },
  { id: 523, text: "Chấp nhận bản thân là bài học dài hơn bất kỳ khóa học nào", category: "trietly" },
  { id: 524, text: "Nhiều lúc ta không cần lời khuyên chỉ cần một chỗ để thở", category: "trietly" },
  { id: 525, text: "Đôi khi dũng cảm nhất là thừa nhận mình đang không ổn", category: "trietly" },
  { id: 526, text: "Hạnh phúc nhỏ khó nhận ra vì ta hay nhìn về phía điều lớn hơn", category: "trietly" },
  { id: 527, text: "Ta tưởng quên rồi cho đến khi một chi tiết nhỏ kéo mọi thứ về", category: "trietly" },
  { id: 528, text: "Nỗi sợ lớn nhất nhiều khi là sống khác với đám đông", category: "trietly" },
  { id: 529, text: "Cuộc đời không luôn công bằng nhưng vẫn mở đường cho người biết đi tiếp", category: "trietly" },
  { id: 530, text: "Có những buổi tối ta không buồn ai chỉ là buồn chính mình", category: "trietly" },
];
