// TROLL — NGHÈO & TÀI CHÍNH
const trollNgheo = [
  { id: 16, text: "Nghèo nhưng vẫn cà phê sữa đá mỗi ngày thôi", category: "ngheo" },
  { id: 17, text: "Lương về chưa kịp nóng tay đã bay qua ví MoMo", category: "ngheo" },
  { id: 18, text: "Đầu tháng như đại gia cuối tháng ăn mì tôm", category: "ngheo" },
  { id: 19, text: "Mình không nghèo mình chỉ đang tiết kiệm thôi", category: "ngheo" },
  { id: 20, text: "Shopee giao hàng nhiều hơn bạn bè đến thăm", category: "ngheo" },
  { id: 21, text: "Ví mỏng nhưng mơ ước thì dày lắm luôn á", category: "ngheo" },
  { id: 22, text: "Tiền tiết kiệm bằng hai bữa trà sữa à", category: "ngheo" },
  { id: 23, text: "Cuối tháng nhìn tài khoản mà muốn gọi điện cho mẹ", category: "ngheo" },
  { id: 24, text: "Giảm giá là lý do duy nhất mình chạy nhanh", category: "ngheo" },
  { id: 25, text: "Thu nhập bốn triệu mà chi tiêu như bốn mươi", category: "ngheo" },
  { id: 26, text: "Bạn bè rủ đi chơi mà ví không cho phép", category: "ngheo" },
  { id: 27, text: "Cơm nhà ăn ngon hơn vì nó miễn phí", category: "ngheo" },
  { id: 176, text: "Lương chưa về mà wishlist đã họp báo công bố kế hoạch", category: "ngheo" },
  { id: 177, text: "Mở app ngân hàng xong tự động sống chậm lại để bớt sốc", category: "ngheo" },
  { id: 178, text: "Có tiền không mua được tất cả nhưng hết tiền thì mua gì cũng khó", category: "ngheo" },
  { id: 179, text: "Thẻ còn hạn mức nên lòng cứ tưởng mình giàu thật", category: "ngheo" },
  { id: 180, text: "Cuối tháng đi siêu thị là nghệ thuật né quầy không cần thiết", category: "ngheo" },
  { id: 181, text: "Ăn ngoài một bữa xong về nhà mở Excel sám hối", category: "ngheo" },
  { id: 182, text: "Ví điện tử báo số dư thấp hơn pin điện thoại", category: "ngheo" },
  { id: 183, text: "Bạn bè nói đầu tư còn mình đầu tư vào ngủ để quên nghèo", category: "ngheo" },
  { id: 184, text: "Lý tưởng tài chính là tiết kiệm thực tế là săn mã giảm giá", category: "ngheo" },
  { id: 185, text: "Nhìn giá xăng tăng mà xe máy cũng muốn khóc theo", category: "ngheo" },
  { id: 186, text: "Tài khoản của mình mỏng manh hơn lòng tự trọng cuối tháng", category: "ngheo" },
  { id: 187, text: "Không phải mình keo chỉ là ngân sách cần được tôn trọng", category: "ngheo" },
  { id: 188, text: "Đặt đồ ăn xong mới nhớ mình đang theo đuổi tự do tài chính", category: "ngheo" },
  { id: 189, text: "Tiền không cánh mà bay còn mình không cánh mà vẫn lao vào sale", category: "ngheo" },
  { id: 190, text: "Bạn hỏi sao không đi du lịch vì số dư thích ở nhà", category: "ngheo" },
  { id: 191, text: "Mỗi lần hoàn tiền là mình cảm giác như vừa được đầu tư thành công", category: "ngheo" },
  { id: 192, text: "Đi chợ xong biết ngay trưởng thành là nhìn giá rồi thở dài", category: "ngheo" },
  { id: 193, text: "Giấc mơ lớn nhất hiện tại là tài khoản không báo giao dịch thất bại", category: "ngheo" },
  { id: 391, text: "Lương vừa vào tài khoản thì hóa đơn đứng xếp hàng chờ sẵn", category: "ngheo" },
  { id: 392, text: "Tiết kiệm khó nhất không phải ít tiền mà là nhiều cám dỗ", category: "ngheo" },
  { id: 393, text: "Đi ngang quán cà phê là ví tự động giả vờ mất sóng", category: "ngheo" },
  { id: 394, text: "Người giàu mua vì thích còn mình mua vì miễn phí vận chuyển", category: "ngheo" },
  { id: 395, text: "Muốn sống sang nhưng ngân sách cứ định hướng sống lành mạnh tại nhà", category: "ngheo" },
  { id: 396, text: "Cuối tháng nhìn app ngân hàng mà nghe lòng nhẹ như gió vì trống", category: "ngheo" },
  { id: 397, text: "Cứ mỗi đợt sale là mình hiểu thêm vì sao khó giàu", category: "ngheo" },
  { id: 398, text: "Khả năng tài chính không ổn nhưng khả năng chốt đơn thì ổn áp", category: "ngheo" },
  { id: 399, text: "Mình không nghèo tạm thời mình đang để tiền nghỉ ngơi", category: "ngheo" },
  { id: 400, text: "Có những ngày ví lép đến mức nghe tiếng kéo khóa cũng buồn", category: "ngheo" },
  { id: 401, text: "Ra cây ATM như đi gặp người yêu cũ vì biết là sẽ thất vọng", category: "ngheo" },
  { id: 402, text: "Tiền ăn với tiền chơi luôn có chiến tranh lạnh trong đầu mình", category: "ngheo" },
  { id: 403, text: "Giỏi nhất không phải kiếm tiền mà là kéo dài số dư đến cuối tháng", category: "ngheo" },
  { id: 404, text: "Ước mơ mua nhà hiện tại vẫn đang sống cùng ước mơ mua trà sữa", category: "ngheo" },
  { id: 405, text: "Ví mỏng nên mỗi quyết định mua hàng đều cần hội đồng đạo đức", category: "ngheo" },
  { id: 406, text: "Không vay ai cũng là một dạng giàu tinh thần rồi", category: "ngheo" },
  { id: 407, text: "Đầu tư tốt nhất tháng này là nấu cơm ở nhà ba bữa", category: "ngheo" },
  { id: 408, text: "Cuộc chiến lớn nhất là giữa nút mua ngay và lương chưa về", category: "ngheo" },
  { id: 409, text: "Có khuyến mãi là tim sáng lên trước khi tài khoản kịp phản đối", category: "ngheo" },
  { id: 410, text: "Điều khiến mình giàu cảm xúc nhất tháng này là hóa đơn điện nước", category: "ngheo" },
];
