// TROLL — ĐỜI SỐNG HÀNG NGÀY
const trollDaily = [
  { id: 70, text: "Sáng nào cũng tự hứa dậy sớm rồi nhấn snooze", category: "daily" },
  { id: 71, text: "Giảm cân bắt đầu từ ngày mai mãi mãi", category: "daily" },
  { id: 72, text: "Kế hoạch thì hoành tráng thực hiện thì hẻo", category: "daily" },
  { id: 73, text: "Nói đi ngủ sớm nhưng 2 giờ sáng vẫn lướt", category: "daily" },
  { id: 74, text: "Tập gym được ba ngày rồi cơ bắp nghỉ luôn", category: "daily" },
  { id: 75, text: "Nấu ăn một lần xong tự phong là siêu đầu bếp", category: "daily" },
  { id: 76, text: "Dọn phòng xong chụp ảnh rồi lại bừa", category: "daily" },
  { id: 77, text: "Hẹn đi cà phê làm việc nhưng chỉ uống cà phê", category: "daily" },
  { id: 78, text: "Nói rằng ổn trong khi không ổn tí nào", category: "daily" },
  { id: 79, text: "Đặt mười cái alarm mà vẫn dậy trễ như thường", category: "daily" },
  { id: 80, text: "Hứa với bản thân năm mới sẽ khác nhưng vẫn tệ", category: "daily" },
  { id: 272, text: "Việc nhà luôn xuất hiện đúng lúc mình định nghỉ ngơi", category: "daily" },
  { id: 273, text: "Mua đồ healthy xong tối lại gọi trà sữa size lớn", category: "daily" },
  { id: 274, text: "Checklist dài lắm nhưng cuối ngày chỉ tick được chuyện ăn trưa", category: "daily" },
  { id: 275, text: "Ra khỏi nhà là quên một thứ quan trọng như định mệnh", category: "daily" },
  { id: 276, text: "Đã mệt còn phải nghĩ hôm nay ăn gì là mệt gấp đôi", category: "daily" },
  { id: 277, text: "Tối nào cũng dặn lòng ngủ sớm để sáng mai không hối hận", category: "daily" },
  { id: 278, text: "Làm xong việc nhỏ là tự thưởng như vừa chinh phục thế giới", category: "daily" },
  { id: 279, text: "Mưa rơi đúng lúc giặt đồ là bài test niềm tin cuộc sống", category: "daily" },
  { id: 280, text: "Nhà sạch được một buổi rồi mọi thứ trở về bản năng", category: "daily" },
  { id: 281, text: "Hôm nay tiêu ít hơn hôm qua nên tự nhận là người biết quản lý", category: "daily" },
  { id: 282, text: "Bận rộn cả ngày nhưng tối vẫn không nhớ mình đã làm gì", category: "daily" },
  { id: 283, text: "Muốn sống tối giản nhưng đồ linh tinh cứ tự sinh sôi", category: "daily" },
  { id: 284, text: "Ngày nghỉ mà vẫn nghĩ đến việc chưa làm nên nghỉ cũng không yên", category: "daily" },
  { id: 285, text: "Chỉ định nằm năm phút rồi ngủ quên đến cả tiếng", category: "daily" },
  { id: 286, text: "Đi siêu thị mua một món xong mang về mười món ngoài kế hoạch", category: "daily" },
  { id: 287, text: "Mỗi sáng tự nhủ tích cực lên rồi gặp tắc đường là quên ngay", category: "daily" },
  { id: 288, text: "Đời sống người lớn là vừa rửa bát vừa nghĩ về hóa đơn", category: "daily" },
  { id: 289, text: "Có những ngày chỉ cần hết pin xã giao là muốn biến mất", category: "daily" },
  { id: 290, text: "Không cần drama nhưng cuộc sống vẫn tự viết kịch bản nhỏ mỗi ngày", category: "daily" },
  { id: 491, text: "Tự dặn uống nhiều nước nhưng đến tối chai nước vẫn gần như nguyên", category: "daily" },
  { id: 492, text: "Mỗi ngày đều muốn làm lại cuộc đời sau một giấc ngủ đủ", category: "daily" },
  { id: 493, text: "Đi ngủ với danh sách việc cần làm rồi sáng dậy quên mất một nửa", category: "daily" },
  { id: 494, text: "Cơm hộp hôm nay ăn ngon hay không phụ thuộc vào tâm trạng đầu giờ chiều", category: "daily" },
  { id: 495, text: "Dọn nhà xong thấy đời có ý nghĩa thêm khoảng ba mươi phút", category: "daily" },
  { id: 496, text: "Ra đường quên tai nghe là cảm giác lạc lõng rất hiện đại", category: "daily" },
  { id: 497, text: "Có hôm bận từ sáng đến tối nhưng thành tựu lớn nhất là không bỏ bữa", category: "daily" },
  { id: 498, text: "Quần áo vẫn nhiều nhưng sáng nào cũng thấy không có gì để mặc", category: "daily" },
  { id: 499, text: "Mỗi lần khóa cửa xong lại nghi mình chưa khóa là một nghi thức", category: "daily" },
  { id: 500, text: "Đi làm về mệt nhưng vẫn đứng nghĩ ăn gì trước tủ lạnh khá lâu", category: "daily" },
  { id: 501, text: "Ngày đẹp trời nhất là ngày không ai gọi điện hỏi chuyện gấp", category: "daily" },
  { id: 502, text: "Rửa ly một cái xong tự tưởng mình là người sống có tổ chức", category: "daily" },
  { id: 503, text: "Mỗi buổi chiều đều có một phiên bản mình muốn xin về sớm", category: "daily" },
  { id: 504, text: "Đói bụng làm mọi quyết định trong ngày trở nên thiếu nhân văn", category: "daily" },
  { id: 505, text: "Nghỉ trưa ít phút mà ngủ dậy tưởng mình vừa sống kiếp khác", category: "daily" },
  { id: 506, text: "Có ngày mọi thứ ổn chỉ vì cà phê sáng không bị đắng quá", category: "daily" },
  { id: 507, text: "Muốn chăm sóc bản thân nhưng trước hết phải nhớ thay ga giường", category: "daily" },
  { id: 508, text: "Mỗi tối đều lên kế hoạch kỹ lưỡng cho một sáng mai không chắc hợp tác", category: "daily" },
  { id: 509, text: "Đời sống bận rộn là vừa ăn vừa nhìn đồng hồ vừa thấy mệt", category: "daily" },
  { id: 510, text: "Đi qua một ngày yên ổn đôi khi đã là may mắn đủ lớn", category: "daily" },
];
