// TROLL — MẠNG XÃ HỘI & ĐỜI SỐNG SỐ
const trollMxh = [
  { id: 50, text: "Sống ảo thì sướng còn sống thật thì ảo", category: "mxh" },
  { id: 51, text: "WiFi mất là mất luôn lý do sống", category: "mxh" },
  { id: 52, text: "Đăng story buồn rồi đếm người xem", category: "mxh" },
  { id: 53, text: "Online hai bốn trên bảy mà bảo bận không rep", category: "mxh" },
  { id: 54, text: "Follow crush xong unfollow rồi follow lại", category: "mxh" },
  { id: 55, text: "Chụp selfie năm mươi tấm mà chỉ đăng một", category: "mxh" },
  { id: 56, text: "Lướt TikTok năm phút mà mất hai tiếng", category: "mxh" },
  { id: 57, text: "Sáng mở mắt ra việc đầu tiên là cầm điện thoại", category: "mxh" },
  { id: 58, text: "Đăng ảnh đẹp mà không ai like thì xóa luôn", category: "mxh" },
  { id: 59, text: "Người ta đi du lịch còn mình du lịch qua màn hình", category: "mxh" },
  { id: 232, text: "Đang làm việc mà tay tự mở mạng xã hội như phản xạ sinh tồn", category: "mxh" },
  { id: 233, text: "Comment dạo xong tự tưởng mình là chuyên gia mọi lĩnh vực", category: "mxh" },
  { id: 234, text: "Một chiếc reel ngắn đủ lấy đi cả buổi tối có trách nhiệm", category: "mxh" },
  { id: 235, text: "Mạng xã hội giúp ta cập nhật thiên hạ và bỏ quên bản thân", category: "mxh" },
  { id: 236, text: "Đăng bài xong giả vờ không quan tâm nhưng năm phút mở lại một lần", category: "mxh" },
  { id: 237, text: "Gõ status dài rồi cuối cùng xóa hết chỉ đăng một dấu chấm", category: "mxh" },
  { id: 238, text: "Online thấy nhau cả ngày nhưng ngoài đời hẹn mãi không gặp", category: "mxh" },
  { id: 239, text: "Thuật toán hiểu mình hơn vài người bạn cũ", category: "mxh" },
  { id: 240, text: "Lướt bình luận đôi lúc còn hấp dẫn hơn nội dung chính", category: "mxh" },
  { id: 241, text: "Đọc tin tiêu cực nhiều quá nên niềm vui cũng cần bộ lọc", category: "mxh" },
  { id: 242, text: "Chỉ định xem thông báo một phút mà nửa tiếng sau vẫn chưa thoát", category: "mxh" },
  { id: 243, text: "Có người yêu nhau nhờ mạng xã hội có người tự ám ảnh cũng từ đó", category: "mxh" },
  { id: 244, text: "Follow nhiều người quá đến lúc buồn không biết unfollow cảm xúc nào trước", category: "mxh" },
  { id: 245, text: "Mạng lag một chút là mình nhận ra cuộc đời còn nhiều thứ khác", category: "mxh" },
  { id: 246, text: "Avatar đổi liên tục nhưng tâm trạng thì vẫn một màu hỗn loạn", category: "mxh" },
  { id: 247, text: "Đăng quote trưởng thành xong vẫn thức đến ba giờ sáng", category: "mxh" },
  { id: 248, text: "Có những cuộc tranh luận online chỉ làm pin yếu và lòng mệt", category: "mxh" },
  { id: 249, text: "Bật thông báo cho crush nhưng giả vờ nói không để ý", category: "mxh" },
  { id: 250, text: "Story biến mất sau hai mươi bốn giờ nhưng mình suy nghĩ về nó cả tuần", category: "mxh" },
  { id: 251, text: "Mạng xã hội là nơi ai cũng ổn cho đến khi tắt màn hình", category: "mxh" },
  { id: 451, text: "Một chiếc thông báo đỏ nhỏ bé đủ làm mình đổi hướng cả ngày", category: "mxh" },
  { id: 452, text: "Có khi mình không buồn chỉ là xem quá nhiều nội dung buồn", category: "mxh" },
  { id: 453, text: "Mỗi nền tảng một tính cách khiến mình sống đa nhân cách nhẹ", category: "mxh" },
  { id: 454, text: "Đăng bài lúc đẹp trời để tối về kiểm tra tương tác như chấm thi", category: "mxh" },
  { id: 455, text: "Mạng xã hội làm thời gian trôi nhanh hơn cả lương tháng", category: "mxh" },
  { id: 456, text: "Thấy ai cũng thành công online nên mình quên ai cũng có ngày tệ", category: "mxh" },
  { id: 457, text: "Vào xem một video nấu ăn xong ra với mười video drama", category: "mxh" },
  { id: 458, text: "Có những đêm chỉ định coi một chút rồi trời sáng lúc nào không hay", category: "mxh" },
  { id: 459, text: "Tự dặn đặt điện thoại xuống nhưng tay không chịu hợp tác", category: "mxh" },
  { id: 460, text: "Ai cũng có thể thành bạn thân trên mạng cho đến khi mượn tiền", category: "mxh" },
  { id: 461, text: "Mình lưu quá nhiều video phát triển bản thân nhưng vẫn đang nằm", category: "mxh" },
  { id: 462, text: "Cứ nói detox mạng xã hội nhưng vẫn vào xem coi ai đang sống ra sao", category: "mxh" },
  { id: 463, text: "Tin nhắn không đến thì buồn mà đến nhiều quá lại mệt", category: "mxh" },
  { id: 464, text: "Có hôm mạng nhanh nhưng tâm trạng không kịp tải", category: "mxh" },
  { id: 465, text: "Lướt đến video thứ ba mươi thì mới nhớ mình vào đây để làm gì", category: "mxh" },
  { id: 466, text: "Thuật toán thấy mình yếu lòng nên đề xuất đúng thứ làm mình suy", category: "mxh" },
  { id: 467, text: "Ảnh chụp một giây nhưng chỉnh cả tiếng để đăng mười phút", category: "mxh" },
  { id: 468, text: "Người bận thật thường ít đăng còn người rảnh thì livestream tâm trạng", category: "mxh" },
  { id: 469, text: "Mỗi lần mất mạng là cơ hội hiếm hoi để nghe tiếng lòng thật", category: "mxh" },
  { id: 470, text: "Có những mối quan hệ chỉ sống bằng icon thả tim và xem story", category: "mxh" },
];
