// TROLL — HỌC HÀNH & THI CỬ
const trollHoctap = [
  { id: 60, text: "Thi xong biết đáp án mà muốn khóc", category: "hoctap" },
  { id: 61, text: "Ôn bài cả đêm mà vào thi quên sạch", category: "hoctap" },
  { id: 62, text: "Thầy cô bảo đề dễ mà cả lớp trầm cảm", category: "hoctap" },
  { id: 63, text: "Học nhóm là lý do để tụ tập ăn uống", category: "hoctap" },
  { id: 64, text: "GPA đẹp trên giấy nhưng kiến thức bay theo gió", category: "hoctap" },
  { id: 65, text: "Mở sách ra là buồn ngủ đóng sách lại thì lo", category: "hoctap" },
  { id: 66, text: "Bạn bè ôn thi còn mình ôn series", category: "hoctap" },
  { id: 67, text: "Đăng ký môn học mà như đánh bạc", category: "hoctap" },
  { id: 68, text: "Điểm danh xong rồi mở YouTube", category: "hoctap" },
  { id: 69, text: "Hỏi bạn bài tập rồi copy y chang", category: "hoctap" },
  { id: 252, text: "Môn mình học nhiều nhất lại chính là môn qua loa", category: "hoctap" },
  { id: 253, text: "Đầu kỳ đầy hi vọng cuối kỳ đầy file PDF chưa đọc", category: "hoctap" },
  { id: 254, text: "Bài giảng lưu trong máy nhiều hơn kiến thức lưu trong đầu", category: "hoctap" },
  { id: 255, text: "Bạn học giỏi là niềm hi vọng cũng là nguồn áp lực nhẹ", category: "hoctap" },
  { id: 256, text: "Nói ôn từ từ nhưng đến gần thi mới bật chế độ người máy", category: "hoctap" },
  { id: 257, text: "Vừa đọc đề xong đã nhớ tới những quyết định sai của đời mình", category: "hoctap" },
  { id: 258, text: "Mùa thi làm cà phê còn chăm hơn làm người", category: "hoctap" },
  { id: 259, text: "Thời khóa biểu đẹp không cứu nổi tinh thần đi học thứ hai", category: "hoctap" },
  { id: 260, text: "Ngồi bàn đầu để tập trung nhưng vẫn mơ màng như thường", category: "hoctap" },
  { id: 261, text: "Deadline bài tập luôn đoàn kết xuất hiện cùng một tuần", category: "hoctap" },
  { id: 262, text: "Làm bài online mà tab tìm kiếm còn hoạt động nhiều hơn não", category: "hoctap" },
  { id: 263, text: "Học để biết thêm còn thi để biết mình quên được bao nhiêu", category: "hoctap" },
  { id: 264, text: "Giảng viên nói phần này quan trọng là cả lớp bắt đầu tỉnh ngủ", category: "hoctap" },
  { id: 265, text: "Bài tập nhóm thường dạy mình kỹ năng kiên nhẫn nhiều hơn kiến thức", category: "hoctap" },
  { id: 266, text: "Đi thư viện rất chăm nhưng chủ yếu để đổi chỗ buồn ngủ", category: "hoctap" },
  { id: 267, text: "Mỗi lần xem bảng điểm là một lần học cách chấp nhận sự thật", category: "hoctap" },
  { id: 268, text: "Học kỳ mới mở ra cùng lời hứa nghiêm túc hơn nhưng chưa chắc", category: "hoctap" },
  { id: 269, text: "Không có câu nào trong đề giống ví dụ thầy cho là chuyện thường", category: "hoctap" },
  { id: 270, text: "Sách mua đầu kỳ thơm hơn động lực học tập cuối kỳ", category: "hoctap" },
  { id: 271, text: "Qua môn không chỉ nhờ kiến thức mà còn nhờ lòng thương của giảng viên", category: "hoctap" },
  { id: 471, text: "Đề cương dài đến mức đọc xong quên mất mình đang học môn gì", category: "hoctap" },
  { id: 472, text: "Mỗi lần nghe kiểm tra đột xuất là linh hồn muốn tạm vắng mặt", category: "hoctap" },
  { id: 473, text: "Ngồi trong lớp mà tâm trí đã đi ăn trưa từ tiết đầu", category: "hoctap" },
  { id: 474, text: "Tưởng học online đỡ mệt ai ngờ mệt vì vừa học vừa chống buồn ngủ", category: "hoctap" },
  { id: 475, text: "Bạn học chăm khiến mình có cảm giác tội lỗi rất học thuật", category: "hoctap" },
  { id: 476, text: "Học bài một tiếng nghỉ năm phút rồi nghỉ luôn", category: "hoctap" },
  { id: 477, text: "Môn khó nhất thường là môn học vào sáng sớm", category: "hoctap" },
  { id: 478, text: "Lịch thi dồn dập làm mình trưởng thành cấp tốc", category: "hoctap" },
  { id: 479, text: "Mỗi lần nộp bài là cầu nguyện file không lỗi và thầy cô thương", category: "hoctap" },
  { id: 480, text: "Bạn bảo ôn sơ sơ thôi nhưng kiến thức của bạn dày như giáo trình", category: "hoctap" },
  { id: 481, text: "Đi học đúng giờ một tuần là mình thấy bản thân đáng được huy chương", category: "hoctap" },
  { id: 482, text: "Nghĩ đến luận văn là não muốn tự động chuyển chủ đề", category: "hoctap" },
  { id: 483, text: "Học nhiều chưa chắc nhớ nhưng không học chắc chắn hoang mang", category: "hoctap" },
  { id: 484, text: "Đi học mà quên mang não là tình trạng quen thuộc mùa thi", category: "hoctap" },
  { id: 485, text: "Bài tập cá nhân nhưng tinh thần cần cả tập thể cứu trợ", category: "hoctap" },
  { id: 486, text: "Có hôm đọc một trang sách mà tâm hồn đi lạc bốn phương", category: "hoctap" },
  { id: 487, text: "Mỗi lần hỏi thầy cô là lại lộ thêm mình chưa hiểu gì", category: "hoctap" },
  { id: 488, text: "Qua được môn khó xong tự tin như vừa đánh boss", category: "hoctap" },
  { id: 489, text: "Đến mùa thi là bàn học tự nhiên sạch sẽ như chuẩn bị nghi lễ", category: "hoctap" },
  { id: 490, text: "Học không khó khó là mở tài liệu lên mà không mở tab khác", category: "hoctap" },
];
