// TROLL — CRUSH & TÌNH YÊU
const trollCrush = [
  { id: 1, text: "Crush rep chậm là đang chat với người khác à", category: "crush" },
  { id: 2, text: "Thà ế chứ không thà yêu lại người cũ", category: "crush" },
  { id: 3, text: "Crush online mà không like story thì coi như xong", category: "crush" },
  { id: 4, text: "Yêu xa là yêu cái nỗi nhớ thôi chứ yêu gì người", category: "crush" },
  { id: 5, text: "Single vì chuẩn cao chứ không phải vì ế đâu nha", category: "crush" },
  { id: 6, text: "Người ta đổi trạng thái còn mình đổi ảnh đại diện", category: "crush" },
  { id: 7, text: "Chat vui lắm rồi để đấy quên rep luôn", category: "crush" },
  { id: 8, text: "Crush đăng story với người khác mà bảo bạn thân", category: "crush" },
  { id: 9, text: "Thất tình rồi lại lên mạng đọc quote buồn", category: "crush" },
  { id: 10, text: "Ngày Valentine mình với con mèo nhìn nhau rồi cười", category: "crush" },
  { id: 11, text: "Mình thích bạn nhưng bạn thích người thích bạn của mình", category: "crush" },
  { id: 12, text: "Nói chuyện mỗi ngày mà bảo chúng mình chỉ là bạn", category: "crush" },
  { id: 13, text: "Duyên phận là câu chuyện mà số phận viết sai chính tả", category: "crush" },
  { id: 14, text: "Seen rồi không rep là cũng một dạng bạo lực tinh thần", category: "crush" },
  { id: 15, text: "Thích ai mà không dám nói thì khác gì mua vé mà không đi xem phim", category: "crush" },
  { id: 161, text: "Crush thả tim bài đăng cũ làm tim mình lag một nhịp", category: "crush" },
  { id: 162, text: "Tỏ tình trong đầu cả trăm lần ra đời chỉ dám chào bạn", category: "crush" },
  { id: 163, text: "Nghe nhạc love song mà người yêu thì chưa có bản demo", category: "crush" },
  { id: 164, text: "Crush đổi avatar là mình phân tích như chuyên gia tình báo", category: "crush" },
  { id: 165, text: "Tình yêu đẹp nhất là tình yêu chưa bắt đầu nên chưa đau", category: "crush" },
  { id: 166, text: "Mập mờ lâu quá đến lúc rõ ràng thì thành người dưng", category: "crush" },
  { id: 167, text: "Bạn thân bảo đừng thích nữa nhưng trái tim không cài được", category: "crush" },
  { id: 168, text: "Crush cười một cái là nguyên ngày mình quên cả deadline", category: "crush" },
  { id: 169, text: "Nói là không quan tâm nhưng story nào của crush cũng xem đầu", category: "crush" },
  { id: 170, text: "Đã thích người ta rồi thì red flag cũng nhìn thành đèn lồng", category: "crush" },
  { id: 171, text: "Tình đơn phương là môn thể thao đốt năng lượng mà không có huy chương", category: "crush" },
  { id: 172, text: "Crush hỏi mượn bài là tim mình tự động mở quyền chỉnh sửa", category: "crush" },
  { id: 173, text: "Nửa đêm nhớ người ta xong sáng ra vẫn phải đi làm như thường", category: "crush" },
  { id: 174, text: "Thính người ta thả trúng ai không biết chứ mình dính đầu tiên", category: "crush" },
  { id: 175, text: "Yêu đương gì tầm này khi tin nhắn còn phải nghĩ ba phút mới gửi", category: "crush" },
  { id: 371, text: "Crush chỉ cần hỏi đang làm gì là mình muốn kể cả tiểu sử", category: "crush" },
  { id: 372, text: "Đã bảo quên người ta rồi mà playlist vẫn toàn nhạc nhớ", category: "crush" },
  { id: 373, text: "Crush vô tình đứng gần là não mình tự động treo máy", category: "crush" },
  { id: 374, text: "Một cái haha của crush cũng đủ làm mình phân tích nửa ngày", category: "crush" },
  { id: 375, text: "Muốn làm người yêu crush nhưng hiện tại mới làm khán giả story", category: "crush" },
  { id: 376, text: "Nói không thích nữa nhưng hễ nghe tên người ta là quay đầu", category: "crush" },
  { id: 377, text: "Crush rep một chữ mà mình rep lại như viết thư xin việc", category: "crush" },
  { id: 378, text: "Đơn phương lâu ngày khiến mình giỏi tưởng tượng hơn giỏi yêu", category: "crush" },
  { id: 379, text: "Yêu thầm mệt nhất là không có tư cách để giận", category: "crush" },
  { id: 380, text: "Crush đăng ảnh mới là mình vô xem nhanh hơn nhận lương", category: "crush" },
  { id: 381, text: "Tình cảm của mình rõ ràng còn tình trạng của hai đứa thì mờ", category: "crush" },
  { id: 382, text: "Đôi lúc chỉ cần crush chào buổi sáng là mình sống tử tế cả ngày", category: "crush" },
  { id: 383, text: "Bật cười với cả thế giới nhưng nhắn cho crush thì run tay", category: "crush" },
  { id: 384, text: "Crush chưa yêu mình nhưng đã dạy mình đủ kiểu chờ đợi", category: "crush" },
  { id: 385, text: "Mỗi lần định buông là người ta lại xuất hiện đúng lúc", category: "crush" },
  { id: 386, text: "Tự nhủ không xem nữa nhưng story của crush như nam châm", category: "crush" },
  { id: 387, text: "Mối quan hệ chưa bắt đầu mà mình đã tưởng tượng chia tay ba lần", category: "crush" },
  { id: 388, text: "Người ta vô tư còn mình âm thầm viết cả bộ phim tình cảm", category: "crush" },
  { id: 389, text: "Crush cười với ai cũng vậy nhưng mình lại tưởng có ngoại lệ", category: "crush" },
  { id: 390, text: "Có những người chỉ cần tồn tại là đủ khiến tim mình mất bình tĩnh", category: "crush" },
];
