// TROLL — ĐỜI SỐNG HÀNG NGÀY
const trollDaily = [
  { id: 70, text: "Sáng nào cũng tự hứa dậy sớm rồi nhấn snooze", category: "daily" },
  { id: 71, text: "Giảm cân bắt đầu từ ngày mai mãi mãi", category: "daily" },
  { id: 72, text: "Kế hoạch thì hoành tráng thực hiện thì hẻo", category: "daily" },
  { id: 73, text: "Nói đi ngủ sớm nhưng 2 giờ sáng vẫn lướt", category: "daily" },
  { id: 74, text: "Tập gym được ba ngày rồi cơ bắp nghỉ luôn", category: "daily" },
  { id: 75, text: "Nấu ăn một lần xong tự phong là siêu đầu bếp", category: "daily" },
  { id: 76, text: "Dọn phòng xong chụp ảnh rồi lại bừa", category: "daily" },
  { id: 77, text: "Hẹn đi cà phê làm việc nhưng chỉ uống cà phê", category: "daily" },
  { id: 78, text: "Nói rằng ổn trong khi không ổn tí nào", category: "daily" },
  { id: 79, text: "Đặt mười cái alarm mà vẫn dậy trễ như thường", category: "daily" },
  { id: 80, text: "Hứa với bản thân năm mới sẽ khác nhưng vẫn tệ", category: "daily" },
  { id: 272, text: "Việc nhà luôn xuất hiện đúng lúc mình định nghỉ ngơi", category: "daily" },
  { id: 273, text: "Mua đồ healthy xong tối lại gọi trà sữa size lớn", category: "daily" },
  { id: 274, text: "Checklist dài lắm nhưng cuối ngày chỉ tick được chuyện ăn trưa", category: "daily" },
  { id: 275, text: "Ra khỏi nhà là quên một thứ quan trọng như định mệnh", category: "daily" },
  { id: 276, text: "Đã mệt còn phải nghĩ hôm nay ăn gì là mệt gấp đôi", category: "daily" },
  { id: 277, text: "Tối nào cũng dặn lòng ngủ sớm để sáng mai không hối hận", category: "daily" },
  { id: 278, text: "Làm xong việc nhỏ là tự thưởng như vừa chinh phục thế giới", category: "daily" },
  { id: 279, text: "Mưa rơi đúng lúc giặt đồ là bài test niềm tin cuộc sống", category: "daily" },
  { id: 280, text: "Nhà sạch được một buổi rồi mọi thứ trở về bản năng", category: "daily" },
  { id: 281, text: "Hôm nay tiêu ít hơn hôm qua nên tự nhận là người biết quản lý", category: "daily" },
  { id: 282, text: "Bận rộn cả ngày nhưng tối vẫn không nhớ mình đã làm gì", category: "daily" },
  { id: 283, text: "Muốn sống tối giản nhưng đồ linh tinh cứ tự sinh sôi", category: "daily" },
  { id: 284, text: "Ngày nghỉ mà vẫn nghĩ đến việc chưa làm nên nghỉ cũng không yên", category: "daily" },
  { id: 285, text: "Chỉ định nằm năm phút rồi ngủ quên đến cả tiếng", category: "daily" },
  { id: 286, text: "Đi siêu thị mua một món xong mang về mười món ngoài kế hoạch", category: "daily" },
  { id: 287, text: "Mỗi sáng tự nhủ tích cực lên rồi gặp tắc đường là quên ngay", category: "daily" },
  { id: 288, text: "Đời sống người lớn là vừa rửa bát vừa nghĩ về hóa đơn", category: "daily" },
  { id: 289, text: "Có những ngày chỉ cần hết pin xã giao là muốn biến mất", category: "daily" },
  { id: 290, text: "Không cần drama nhưng cuộc sống vẫn tự viết kịch bản nhỏ mỗi ngày", category: "daily" },
  { id: 491, text: "Tự dặn uống nhiều nước nhưng đến tối chai nước vẫn gần như nguyên", category: "daily" },
  { id: 492, text: "Mỗi ngày đều muốn làm lại cuộc đời sau một giấc ngủ đủ", category: "daily" },
  { id: 493, text: "Đi ngủ với danh sách việc cần làm rồi sáng dậy quên mất một nửa", category: "daily" },
  { id: 494, text: "Cơm hộp hôm nay ăn ngon hay không phụ thuộc vào tâm trạng đầu giờ chiều", category: "daily" },
  { id: 495, text: "Dọn nhà xong thấy đời có ý nghĩa thêm khoảng ba mươi phút", category: "daily" },
  { id: 496, text: "Ra đường quên tai nghe là cảm giác lạc lõng rất hiện đại", category: "daily" },
  { id: 497, text: "Có hôm bận từ sáng đến tối nhưng thành tựu lớn nhất là không bỏ bữa", category: "daily" },
  { id: 498, text: "Quần áo vẫn nhiều nhưng sáng nào cũng thấy không có gì để mặc", category: "daily" },
  { id: 499, text: "Mỗi lần khóa cửa xong lại nghi mình chưa khóa là một nghi thức", category: "daily" },
  { id: 500, text: "Đi làm về mệt nhưng vẫn đứng nghĩ ăn gì trước tủ lạnh khá lâu", category: "daily" },
  { id: 501, text: "Ngày đẹp trời nhất là ngày không ai gọi điện hỏi chuyện gấp", category: "daily" },
  { id: 502, text: "Rửa ly một cái xong tự tưởng mình là người sống có tổ chức", category: "daily" },
  { id: 503, text: "Mỗi buổi chiều đều có một phiên bản mình muốn xin về sớm", category: "daily" },
  { id: 504, text: "Đói bụng làm mọi quyết định trong ngày trở nên thiếu nhân văn", category: "daily" },
  { id: 505, text: "Nghỉ trưa ít phút mà ngủ dậy tưởng mình vừa sống kiếp khác", category: "daily" },
  { id: 506, text: "Có ngày mọi thứ ổn chỉ vì cà phê sáng không bị đắng quá", category: "daily" },
  { id: 507, text: "Muốn chăm sóc bản thân nhưng trước hết phải nhớ thay ga giường", category: "daily" },
  { id: 508, text: "Mỗi tối đều lên kế hoạch kỹ lưỡng cho một sáng mai không chắc hợp tác", category: "daily" },
  { id: 509, text: "Đời sống bận rộn là vừa ăn vừa nhìn đồng hồ vừa thấy mệt", category: "daily" },
  { id: 510, text: "Đi qua một ngày yên ổn đôi khi đã là may mắn đủ lớn", category: "daily" },
  { id: 791, text: "Có hôm mình mệt đến mức quyết định ăn gì cũng thành câu hỏi triết học", category: "daily" },
  { id: 792, text: "Mỗi sáng tìm chìa khóa như một phần không thể thiếu của nghi thức ra đường", category: "daily" },
  { id: 793, text: "Dọn bàn làm việc xong mới có cảm giác mình sắp sống tốt hơn", category: "daily" },
  { id: 794, text: "Mọi việc đang ổn cho tới lúc mình nhớ ra còn quần áo chưa phơi", category: "daily" },
  { id: 795, text: "Đi chợ lúc đói là cách nhanh nhất để về nhà với nhiều quyết định sai", category: "daily" },
  { id: 796, text: "Có ngày chỉ muốn nằm yên mà điện thoại vẫn gọi tên trách nhiệm", category: "daily" },
  { id: 797, text: "Một chiếc giường gọn gàng đủ làm mình tưởng đã kiểm soát được cuộc sống", category: "daily" },
  { id: 798, text: "Mỗi chiều tan làm là một phiên bản pin yếu của chính mình", category: "daily" },
  { id: 799, text: "Đã giặt đồ xong thì trời mới nhớ mình có thể mưa", category: "daily" },
  { id: 800, text: "Lịch sinh hoạt của mình đẹp nhất là trong đầu trước khi ngày bắt đầu", category: "daily" },
  { id: 801, text: "Nấu ăn được một bữa ngon là tự tin như vừa mở nhà hàng", category: "daily" },
  { id: 802, text: "Ra đường quên ví còn đỡ hơn quên điện thoại trong thời đại này", category: "daily" },
  { id: 803, text: "Mỗi lần chốt được một việc nhỏ là mình thấy ngày đỡ vô nghĩa hơn", category: "daily" },
  { id: 804, text: "Có hôm nhà cửa bừa bộn phản ánh tâm hồn rất trung thực", category: "daily" },
  { id: 805, text: "Đi làm người lớn khó nhất là không ai phát huy chương vì rửa bát đúng giờ", category: "daily" },
  { id: 806, text: "Những ngày mưa khiến kế hoạch ra ngoài tự tan như đường trong nước", category: "daily" },
  { id: 807, text: "Mỗi tối dọn mail xong là thấy bản thân sống có trách nhiệm thêm chút", category: "daily" },
  { id: 808, text: "Có ngày quên uống nước đến lúc đau đầu mới nhớ mình là sinh vật sống", category: "daily" },
  { id: 809, text: "Mình định nghỉ ngơi năm phút nhưng cuộc sống rất hay tính theo giờ", category: "daily" },
  { id: 810, text: "Sống một mình là môn học về việc nhớ mua nước rửa chén trước khi hết", category: "daily" },
  { id: 811, text: "Có hôm niềm vui lớn nhất là ra đường không bị kẹt xe", category: "daily" },
  { id: 812, text: "Mỗi lần dọn tủ là lại thấy quá khứ mua sắm của mình không hề vô tội", category: "daily" },
  { id: 813, text: "Ngày nào tự nấu cơm được cũng thấy mình xứng đáng được khen", category: "daily" },
  { id: 814, text: "Có những tối mình không cần gì ngoài im lặng và một chỗ nằm", category: "daily" },
  { id: 815, text: "Đời sống người lớn là nhớ đóng tiền đúng hạn còn lại tính sau", category: "daily" },
  { id: 816, text: "Đi bộ về nhà sau một ngày dài nhiều khi chữa lành hơn cả mua sắm", category: "daily" },
  { id: 817, text: "Mỗi lần hết đồ ăn trong tủ là trách nhiệm trưởng thành gõ cửa", category: "daily" },
  { id: 818, text: "Ngủ trưa đúng hai mươi phút là một ước mơ nghe nhỏ mà khó", category: "daily" },
  { id: 819, text: "Có hôm mặc đồ ổn là tự nhiên thấy tinh thần làm việc tăng nhẹ", category: "daily" },
  { id: 820, text: "Qua được một ngày bình thường tử tế cũng đã là thành tựu đáng kể", category: "daily" },
];
