// TROLL — GIA ĐÌNH & MẸ MẮNG
const trollMe = [
  { id: 40, text: "Mẹ mắng xong rồi gọi ra ăn trái cây", category: "me" },
  { id: 41, text: "Về nhà mà mẹ khen là biết sắp nhờ gì rồi", category: "me" },
  { id: 42, text: "Bố mẹ hỏi bao giờ có người yêu mà mình hỏi lại bao giờ có wifi nhanh hơn", category: "me" },
  { id: 43, text: "Con nhà người ta luôn giỏi hơn con nhà mình", category: "me" },
  { id: 44, text: "Mẹ nói một câu mà đúng hết cả cuộc đời", category: "me" },
  { id: 45, text: "Đi chơi với bạn mà mẹ hỏi đi với ai ở đâu mấy giờ về", category: "me" },
  { id: 46, text: "Mẹ gọi điện ba phút mà tóm tắt được cả cuộc đời", category: "me" },
  { id: 47, text: "Về quê bị hỏi lương bao nhiêu là muốn quay xe", category: "me" },
  { id: 48, text: "Ba nói ít nhưng mỗi câu như búa tạ", category: "me" },
  { id: 49, text: "Mẹ bảo tiết kiệm mà mẹ mua sắm Shopee nhiều hơn con", category: "me" },
  { id: 212, text: "Mẹ gọi ăn cơm ba lần đến lần bốn là gọi bằng tên đầy đủ", category: "me" },
  { id: 213, text: "Ở nhà mười phút là mẹ hỏi đã ăn gì chưa ba lần", category: "me" },
  { id: 214, text: "Mẹ xem mình gầy là muốn bồi bổ cả một siêu thị", category: "me" },
  { id: 215, text: "Đi đâu về muộn một chút là mẹ dựng luôn phim trinh thám", category: "me" },
  { id: 216, text: "Mẹ bảo không cần mua gì về rồi vẫn hỏi sao không mua trái cây", category: "me" },
  { id: 217, text: "Bữa cơm gia đình là nơi mình bị hỏi đủ mọi KPI cuộc đời", category: "me" },
  { id: 218, text: "Mẹ nhớ lịch tiêm của mình còn rõ hơn mình nhớ deadline", category: "me" },
  { id: 219, text: "Đi làm rồi mà trong mắt mẹ vẫn là đứa không biết tự lo", category: "me" },
  { id: 220, text: "Mẹ gửi đồ ăn lên thành phố như đang tiếp tế cho chiến trường", category: "me" },
  { id: 221, text: "Vừa ho một tiếng là mẹ kê đơn bằng kinh nghiệm dân gian", category: "me" },
  { id: 222, text: "Ba ít nói nhưng hỏi một câu là mình phải nghĩ lại cả đời", category: "me" },
  { id: 223, text: "Mẹ bảo ngủ sớm trong khi chính mẹ xem phim đến khuya", category: "me" },
  { id: 224, text: "Chưa kịp kể chuyện buồn thì mẹ đã cắt sẵn đĩa ổi động viên", category: "me" },
  { id: 225, text: "Mẹ mắng thì dữ nhưng ai chê con mẹ là mẹ bênh đầu tiên", category: "me" },
  { id: 226, text: "Về quê hai ngày là lịch ăn uống của mẹ kín hơn lịch công tác", category: "me" },
  { id: 227, text: "Mẹ nhắc áo ấm từ tháng mười dù mình mới hắt hơi một cái", category: "me" },
  { id: 228, text: "Ba hỏi dạo này sao rồi nghe đơn giản mà thấy ấm cả ngày", category: "me" },
  { id: 229, text: "Ở nhà ăn một bữa là mẹ hỏi có muốn mang thêm hộp về không", category: "me" },
  { id: 230, text: "Nghe tiếng xe ngoài ngõ là mẹ biết con về trước cả camera", category: "me" },
  { id: 231, text: "Mẹ nói tiết kiệm điện nhưng quạt bật cho con ngủ thì không tiếc", category: "me" },
  { id: 431, text: "Mẹ hỏi có ăn sáng chưa bằng giọng biết chắc là mình chưa ăn", category: "me" },
  { id: 432, text: "Ba ít nhắn tin nhưng mỗi lần nhắn là hỏi đủ chuyện thiết thực", category: "me" },
  { id: 433, text: "Mẹ bảo không lo gì đâu xong vẫn gọi kiểm tra ba lượt", category: "me" },
  { id: 434, text: "Tủ lạnh nhà có đồ ăn là vì mẹ tin con mình luôn đói", category: "me" },
  { id: 435, text: "Mẹ than con lớn rồi nhưng vẫn cắt sẵn trái cây để trên bàn", category: "me" },
  { id: 436, text: "Ba sửa đồ trong nhà như thể mọi thứ đều có thể cứu được", category: "me" },
  { id: 437, text: "Mẹ nhớ mình thích ăn gì rõ hơn mình nhớ lịch thanh toán", category: "me" },
  { id: 438, text: "Về nhà là tự động thành người nhỏ nhất dù ngoài kia đã đi làm", category: "me" },
  { id: 439, text: "Mẹ nói chuyện với hàng xóm xong biết luôn tình hình của cả xóm", category: "me" },
  { id: 440, text: "Ba chở đi đâu cũng hỏi lạnh không dù trời đang nóng", category: "me" },
  { id: 441, text: "Mẹ gọi đúng lúc mình vừa tính bỏ bữa nên không dám nói dối lâu", category: "me" },
  { id: 442, text: "Nhà là nơi tóc tai bù xù cũng vẫn được ăn ngon mặc ấm", category: "me" },
  { id: 443, text: "Mẹ dặn mang theo ô như thể mây cũng nghe lời mẹ", category: "me" },
  { id: 444, text: "Ba không nói thương nhiều nhưng hễ xe hỏng là có mặt ngay", category: "me" },
  { id: 445, text: "Mỗi lần về quê là cân nặng bị mẹ đối xử rất tích cực", category: "me" },
  { id: 446, text: "Mẹ hay cằn nhằn nhưng hễ con im lặng là mẹ lại lo", category: "me" },
  { id: 447, text: "Ba mẹ hay hỏi chuyện tương lai vì thật ra chỉ mong mình ổn", category: "me" },
  { id: 448, text: "Nghe mẹ kể chuyện xưa là biết mình giống ai trong khoản bướng", category: "me" },
  { id: 449, text: "Nhà không phải nơi hoàn hảo nhưng luôn là nơi có chỗ cho mình", category: "me" },
  { id: 450, text: "Mẹ bảo cứ về nhà đi rồi tính tiếp câu đó nghe là thấy nhẹ", category: "me" },
];
